### ISSUE TITLE
It's good, but... It's bad.

### ISSUE THREAD

**Issue by muezis** [RuoyanMeng/lyrics_crawler_client#1]
Hey, It's really good. This is probably the only app that allows me to select, copy, and perform other actions with text. But there is one problem. Player. It's very inconvenient that it's at the top of the page. I'm reading the lyrics, I'm close to the end, and I want to pause - I have to go back up the page. And I even can't rewind it. Why? I learn the language by reading the lyrics, and it is important for me to be able to rewind and pause to listen a particular phrase again.

So far, your app isn't much better than just opening text on genius. But if you make a normal player that can be conveniently controlled, it will be the best that is available at the moment.

**Comment by RuoyanMeng** [comment]
> Hey, It's really good. This is probably the only app that allows me to select, copy, and perform other actions with text. But there is one problem. Player. It's very inconvenient that it's at the top of the page. I'm reading the lyrics, I'm close to the end, and I want to pause - I have to go back up the page. And I even can't rewind it. Why? I learn the language by reading the lyrics, and it is important for me to be able to rewind and pause to listen a particular phrase again.
> 
> So far, your app isn't much better than just opening text on genius. But if you make a normal player that can be conveniently controlled, it will be the best that is available at the moment.

Hi, thank you for your kind suggestion. I will improve the player position issue in the next release, and a more convenient player with full functions will be updated in the future.

**Comment by RuoyanMeng** [comment]
Problem solved,  see the latest commit
